// LOCALHOST 
### Get all contacts
GET http://localhost:8080/contacts 

### Get contact by id
GET http://localhost:8080/contacts/6266653a3ab106ada3ea9b91 

### Create contact (insert data)
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Derick",
    "lastName":"Deklerk",
    "email":"zedericke@test.com",
    "favoriteColor":"Marron",
    "birthday":"06/19/1988"
}

### PUT contact (Update data)
PUT http://localhost:8080/contacts/6267f9b4e576d23ccfe53992 HTTP/1.1
content-type: application/json

{
    "firstName":"Derick wa Ka",
    "lastName":"Deklerk wa",
    "email":"zedericke@test.com2",
    "favoriteColor":"Marron2",
    "birthday":"06/19/19882"
}

### DELETE contact
DELETE http://localhost:8080/contacts/6220b775099269ff7b31ceab HTTP/1.1



// PRODUCTION Deploy 

### Get all contacts
GET https://cse341-fab.herokuapp.com/contacts 

### Get contact by id
GET https://cse341-fab.herokuapp.com/contacts/6267ec3b64d5cb69e57862e3

### Create contact
POST https://cse341-fab.herokuapp.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Mirade",
    "lastName":"Francis",
    "email":"alino@test.com",
    "favoriteColor":"Blue",
    "birthday":"06/14/1980"
}

### PUT contact
PUT https://cse341-fab.herokuapp.com/contacts/6267ec3b64d5cb69e57862e3 HTTP/1.1
content-type: application/json

{
    "firstName":"Alain Gizaza",
    "lastName":"Ngandu",
    "email":"alino@test.com",
    "favoriteColor":"Blue",
    "birthday":"06/14/1980"
}


### DELETE contact
DELETE https://cse341-fab.herokuapp.com/contacts/6267f1183e1d6800448b37d3 HTTP/1.1